### ISSUE TITLE
Fetcher failure

### ISSUE THREAD

**Issue by maku0** [tibbotech/yocto_layers#10]
I have pulled last changes and tried to compile, but I get error:

bitbake img-spmn

WARNING: mc:tpp-tppg2-arm5:xboot-tools-native-gh-r0 do_fetch: Failed to fetch URL git://github.com/tibbotech/plus1_draminit.git;name=draminit;branch=master;destsuffix=draminit;, attempting MIRRORS if available
ERROR: mc:tpp-tppg2-arm5:xboot-tools-native-gh-r0 do_fetch: Fetcher failure: Unable to find revision 1e5f063b3a79169662fc18cf71f0f2668f775d4b in branch master even from upstream
ERROR: mc:tpp-tppg2-arm5:xboot-tools-native-gh-r0 do_fetch: Fetcher failure for URL: 'git://github.com/tibbotech/plus1_draminit.git;name=draminit;branch=master;destsuffix=draminit;'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /disk2/build.24/tmp/work/x86_64-linux/xboot-tools-native/gh-r0/temp/log.do_fetch.13207
ERROR: Task (mc:tpp-tppg2-arm5:virtual:native:/usr/yoctoPlus2/poky/c.tppg2/../meta-sunplus/recipes-bsp/xboot/xboot-tools_gh.bb:do_fetch) failed with exit code '1'

**Comment by dmitrydvorkin** [comment]
New version with new indexes is pushed. Sorry!

**Comment by maku0** [comment]
Ok I've resolved by changing 
#SRCREV_draminit = "1e5f063b3a79169662fc18cf71f0f2668f775d4b"
SRCREV_draminit = "24513aa60fa4125a885e4714d4b3937ee91e1135"
in xboot-src-gh.inc
