### ISSUE TITLE
Kernel warning

### ISSUE THREAD

**Issue by maku0** [tibbotech/yocto_layers#11]
I dont know if it's importand, just for information, during bitbake bitbake img-spmn:

First warning:
Parsing of 2630 .bb files complete (2597 cached, 33 parsed). 15404 targets, 399 skipped, 0 masked, 0 errors.
WARNING: No bb files matched BBFILE_PATTERN_tibbopriv '^/usr/yoctoPlus2/poky/c.tppg2/../meta-tibbopriv/'
WARNING: No bb files matched BBFILE_PATTERN_tibbopriv '^/usr/yoctoPlus2/poky/c.tppg2/../meta-tibbopriv/'
WARNING: No bb files matched BBFILE_PATTERN_tibbopriv '^/usr/yoctoPlus2/poky/c.tppg2/../meta-tibbopriv/'
WARNING: No bb files matched BBFILE_PATTERN_tibbopriv '^/usr/yoctoPlus2/poky/c.tppg2/../meta-tibbopriv/'

And second warning:

WARNING: mc:tpp-tppg2:linux-sprel-4.19.37+gitAUTOINC+277821b48c-r0 do_kernel_configcheck: [kernel config]: specified values did not make it into the kernel's final configuration:

---------- CONFIG_DEBUG_UART_PHYS -----------------
Config: CONFIG_DEBUG_UART_PHYS
From: /disk2/build.24/tmp/work-shared/tppg2/kernel-source/.kernel-meta/configs/tiny/pentagram/tppg2/kernel-meta/bsp/pentagram/pentagram.cfg
Requested value:  CONFIG_DEBUG_UART_PHYS=0x9c000900
Actual value:     

No symbol DEBUG_UART_PHYS exists in the configuration

---------- CONFIG_DEBUG_UART_VIRT -----------------
Config: CONFIG_DEBUG_UART_VIRT
From: /disk2/build.24/tmp/work-shared/tppg2/kernel-source/.kernel-meta/configs/tiny/pentagram/tppg2/kernel-meta/bsp/pentagram/pentagram.cfg
Requested value:  CONFIG_DEBUG_UART_VIRT=0xf8000900
Actual value:     

No symbol DEBUG_UART_VIRT exists in the configuration

---------- CONFIG_I2C_SMBUS -----------------
Config: CONFIG_I2C_SMBUS
From: /disk2/build.24/tmp/work-shared/tppg2/kernel-source/.kernel-meta/configs/tiny/pentagram/tppg2/kernel-meta/bsp/pentagram/hw_i2c.cfg
Requested value:  CONFIG_I2C_SMBUS=m
Actual value:     

  Config 'I2C_SMBUS' has the following Direct dependencies (=y):
        I2C(=y)

---------- CONFIG_BCMDHD_WEXT -----------------
Config: CONFIG_BCMDHD_WEXT
From: /disk2/build.24/tmp/work-shared/tppg2/kernel-source/.kernel-meta/configs/tiny/pentagram/tppg2/kernel-meta/bsp/pentagram/wifi/tppg2_brcm.cfg
Requested value:  CONFIG_BCMDHD_WEXT=y
Actual value:     

No reference to BCMDHD_WEXT found

---------- CONFIG_CAN_C_CAN_PCI -----------------
Config: CONFIG_CAN_C_CAN_PCI
From: /disk2/build.24/tmp/work-shared/tppg2/kernel-source/.kernel-meta/configs/tiny/pentagram/features/can/can.cfg
Requested value:  CONFIG_CAN_C_CAN_PCI=m
Actual value:     

No reference to CAN_C_CAN_PCI found

---------- CONFIG_CAN_EMS_PCI -----------------
Config: CONFIG_CAN_EMS_PCI
From: /disk2/build.24/tmp/work-shared/tppg2/kernel-source/.kernel-meta/configs/tiny/pentagram/features/can/can.cfg
Requested value:  CONFIG_CAN_EMS_PCI=m
Actual value:     

No reference to CAN_EMS_PCI found

---------- CONFIG_CAN_PEAK_PCI -----------------
Config: CONFIG_CAN_PEAK_PCI
From: /disk2/build.24/tmp/work-shared/tppg2/kernel-source/.kernel-meta/configs/tiny/pentagram/features/can/can.cfg
Requested value:  CONFIG_CAN_PEAK_PCI=m
Actual value:     

Config: CONFIG_CAN_PEAK_PCIEC
From: /disk2/build.24/tmp/work-shared/tppg2/kernel-source/.kernel-meta/configs/tiny/pentagram/features/can/can.cfg
Requested value:  CONFIG_CAN_PEAK_PCIEC=m
Actual value:     

  Config 'CAN_PEAK_PCI' has the following Direct dependencies (=m):
        PCI(=y) && CAN_SJA1000(=m) && CAN_DEV(=m) && CAN(=m) && NET(=y)

---------- CONFIG_CAN_PEAK_PCIEC -----------------
Config: CONFIG_CAN_PEAK_PCIEC
From: /disk2/build.24/tmp/work-shared/tppg2/kernel-source/.kernel-meta/configs/tiny/pentagram/features/can/can.cfg
Requested value:  CONFIG_CAN_PEAK_PCIEC=m
Actual value:     

No reference to CAN_PEAK_PCIEC found

---------- CONFIG_CAN_KVASER_PCI -----------------
Config: CONFIG_CAN_KVASER_PCI
From: /disk2/build.24/tmp/work-shared/tppg2/kernel-source/.kernel-meta/configs/tiny/pentagram/features/can/can.cfg
Requested value:  CONFIG_CAN_KVASER_PCI=m
Actual value:     

No reference to CAN_KVASER_PCI found

---------- CONFIG_CAN_PLX_PCI -----------------
Config: CONFIG_CAN_PLX_PCI
From: /disk2/build.24/tmp/work-shared/tppg2/kernel-source/.kernel-meta/configs/tiny/pentagram/features/can/can.cfg
Requested value:  CONFIG_CAN_PLX_PCI=m
Actual value:     

No reference to CAN_PLX_PCI found

**Comment by dmitrydvorkin** [comment]
First warning is OK, case tibbopriv is the Tibbo private software layer. Obviously, It is empty for copyright reasons.

Second group of warnings is mostly fixed in upcoming update. Meaningless.
