### ISSUE TITLE
Error in npymath 

### ISSUE THREAD

**Issue by maku0** [tibbotech/yocto_layers#12]
| building 'npymath' library
...
| In file included from numpy/core/src/npymath/npy_math_private.h:25,
|                  from numpy/core/src/npymath/ieee754.c.src:8:
| numpy/core/src/common/npy_fpmath.h:19:6: error: #error No long double representation defined
|    19 |     #error No long double representation defined
|       |      ^~~~~
...
| numpy/core/src/npymath/npy_math_private.h:451:31: error: 'LDBL_EXP_MASK' undeclared (first use in this function)
|   451 |     (((x).a[LDBL_EXP_INDEX] & LDBL_EXP_MASK) >> LDBL_EXP_SHIFT)
|       |                               ^~~~~~~~~~~~~
...
ERROR: Task (mc:tpp-tppg2:/usr/yoctoPlus2/poky/c.tppg2/../meta/recipes-devtools/python-numpy/python3-numpy_1.17.0.bb:do_compile) failed with exit code '1'

**Comment by dmitrydvorkin** [comment]
RLY? Hmmm... What numpy version is in your Poky layers? I have:
[dv@localhost poky (zeus)]$ ls ./meta/recipes-devtools/python-numpy
python3-numpy_1.17.0.bb

**Comment by maku0** [comment]
My mistake, I didnt checkout meta-openembedded to zeus branch
