### ISSUE TITLE
meta-sunplus/recipes-kernel/linux-sprel_%.bbappend  SRCREV is wrong

### ISSUE THREAD

**Issue by erimsa** [tibbotech/yocto_layers#13]
linux-sprel_%.bbpappend file has ;  
KBRANCH = "kernel_4.19"
SRCREV = "2a286661044e3b3b1127e7bb07018992ee19ddcf"

It tries to fetch "linux-sprel-4.19.37+gitAUTOINC+2a28666104-r0" which linux_4.19 branch does not have this commit revision.

Results with ; 
WARNING: linux-sprel-4.19.37+gitAUTOINC+2a28666104-r0 do_fetch: Failed to fetch URL git://github.com/tibbotech/plus1_kernel.git;branch=kernel_4.19;, attempting MIRRORS if available
ERROR: linux-sprel-4.19.37+gitAUTOINC+2a28666104-r0 do_fetch: Fetcher failure: Unable to find revision 2a286661044e3b3b1127e7bb07018992ee19ddcf in branch kernel_4.19 even from upstream
ERROR: linux-sprel-4.19.37+gitAUTOINC+2a28666104-r0 do_fetch: Fetcher failure for URL: 'git://github.com/tibbotech/plus1_kernel.git;branch=kernel_4.19;'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /media/erimsa/mySSD/build.24/tmp/work/tppg2-tps-linux-gnueabi/linux-sprel/4.19.37+gitAUTOINC+2a28666104-r0/temp/log.do_fetch.912753
ERROR: Task (/home/erimsa/Desktop/SpGate/tibbo/tibbotech_yocto/poky/c.tppg2/../meta-sunplus/recipes-kernel/linux/linux-sprel_4.19.bb:do_fetch) failed with exit code '1'

I tried  this commit "eee6766b2540822a9b229f64549299793a903f41" but it fails at kernel patches.

**Comment by dmitrydvorkin** [comment]
you can safely comment-out all kernel patches except this one:
SRC_URI += "file://sp7021-tpsgpio.dts.patch"
