### ISSUE TITLE
ISPBOOOT.BIN not created

### ISSUE THREAD

**Issue by erimsa** [tibbotech/yocto_layers#14]
After built any image, 
"make -f ./sp_make.mk"  
fails with that errors ;

Error for 'isp_script_nand_002c3465': isp.c: 1131
make: *** [sp_make.mk:86: sp_out/ISPBOOOT.BIN] Error 255

**Comment by dmitrydvorkin** [comment]
Please, do
ls -l /disk2/build.26/tmp/deploy/images/tppg2
ls -l /disk2/build.26/tmp/deploy/images/tppg2-arm5
and send me the log.

**Comment by erimsa** [comment]
<pre><font color="#4E9A06"><b>erimsa@probook</b></font>:<font color="#3465A4"><b>~</b></font>$ ls -l /disk2/build.26/tmp/deploy/images/tppg2
total 585600
-rwxr-xr-x 2 erimsa erimsa    491600 Kas  2 01:16 <font color="#4E9A06"><b>dtc</b></font>
-rw-r--r-- 2 erimsa erimsa  88080384 Kas  2 02:52 img-sp-tiny-tppg2-20201101230101.rootfs.ext4
-rw-r--r-- 2 erimsa erimsa      4335 Kas  2 02:43 img-sp-tiny-tppg2-20201101230101.rootfs.manifest
-rw-r--r-- 2 erimsa erimsa  21848064 Kas  2 02:52 img-sp-tiny-tppg2-20201101230101.rootfs.squashfs
-rw-r--r-- 2 erimsa erimsa  20078209 Kas  2 02:52 <font color="#CC0000"><b>img-sp-tiny-tppg2-20201101230101.rootfs.tar.bz2</b></font>
-rw-r--r-- 2 erimsa erimsa  33902592 Kas  2 02:52 img-sp-tiny-tppg2-20201101230101.rootfs.ubi
-rw-r--r-- 2 erimsa erimsa  32505856 Kas  2 02:52 img-sp-tiny-tppg2-20201101230101.rootfs.ubifs
-rw-r--r-- 2 erimsa erimsa    266449 Kas  2 02:43 img-sp-tiny-tppg2-20201101230101.testdata.json
lrwxrwxrwx 2 erimsa erimsa        44 Kas  2 02:52 <font color="#06989A"><b>img-sp-tiny-tppg2.ext4</b></font> -&gt; img-sp-tiny-tppg2-20201101230101.rootfs.ext4
lrwxrwxrwx 2 erimsa erimsa        48 Kas  2 02:43 <font color="#06989A"><b>img-sp-tiny-tppg2.manifest</b></font> -&gt; img-sp-tiny-tppg2-20201101230101.rootfs.manifest
lrwxrwxrwx 2 erimsa erimsa        48 Kas  2 02:52 <font color="#06989A"><b>img-sp-tiny-tppg2.squashfs</b></font> -&gt; img-sp-tiny-tppg2-20201101230101.rootfs.squashfs
lrwxrwxrwx 2 erimsa erimsa        47 Kas  2 02:52 <font color="#06989A"><b>img-sp-tiny-tppg2.tar.bz2</b></font> -&gt; <font color="#CC0000"><b>img-sp-tiny-tppg2-20201101230101.rootfs.tar.bz2</b></font>
lrwxrwxrwx 2 erimsa erimsa        46 Kas  2 02:43 <font color="#06989A"><b>img-sp-tiny-tppg2.testdata.json</b></font> -&gt; img-sp-tiny-tppg2-20201101230101.testdata.json
lrwxrwxrwx 2 erimsa erimsa        43 Kas  2 02:52 <font color="#06989A"><b>img-sp-tiny-tppg2.ubi</b></font> -&gt; img-sp-tiny-tppg2-20201101230101.rootfs.ubi
lrwxrwxrwx 2 erimsa erimsa        45 Kas  2 02:52 <font color="#06989A"><b>img-sp-tiny-tppg2.ubifs</b></font> -&gt; img-sp-tiny-tppg2-20201101230101.rootfs.ubifs
-rw-r--r-- 2 erimsa erimsa 280543232 Kas  2 10:24 img-tps-free-tppg2-20201101230101.rootfs.ext4
-rw-r--r-- 2 erimsa erimsa     10161 Kas  2 02:44 img-tps-free-tppg2-20201101230101.rootfs.manifest
-rw-r--r-- 2 erimsa erimsa  49483776 Kas  2 02:52 img-tps-free-tppg2-20201101230101.rootfs.squashfs
-rw-r--r-- 2 erimsa erimsa  45858885 Kas  2 02:52 <font color="#CC0000"><b>img-tps-free-tppg2-20201101230101.rootfs.tar.bz2</b></font>
-rw-r--r-- 2 erimsa erimsa  79740928 Kas  2 02:52 img-tps-free-tppg2-20201101230101.rootfs.ubi
-rw-r--r-- 2 erimsa erimsa  76820480 Kas  2 02:52 img-tps-free-tppg2-20201101230101.rootfs.ubifs
-rw-r--r-- 2 erimsa erimsa    267814 Kas  2 02:44 img-tps-free-tppg2-20201101230101.testdata.json
lrwxrwxrwx 2 erimsa erimsa        45 Kas  2 02:52 <font color="#06989A"><b>img-tps-free-tppg2.ext4</b></font> -&gt; img-tps-free-tppg2-20201101230101.rootfs.ext4
lrwxrwxrwx 2 erimsa erimsa        49 Kas  2 02:44 <font color="#06989A"><b>img-tps-free-tppg2.manifest</b></font> -&gt; img-tps-free-tppg2-20201101230101.rootfs.manifest
lrwxrwxrwx 2 erimsa erimsa        49 Kas  2 02:52 <font color="#06989A"><b>img-tps-free-tppg2.squashfs</b></font> -&gt; img-tps-free-tppg2-20201101230101.rootfs.squashfs
lrwxrwxrwx 2 erimsa erimsa        48 Kas  2 02:52 <font color="#06989A"><b>img-tps-free-tppg2.tar.bz2</b></font> -&gt; <font color="#CC0000"><b>img-tps-free-tppg2-20201101230101.rootfs.tar.bz2</b></font>
lrwxrwxrwx 2 erimsa erimsa        47 Kas  2 02:44 <font color="#06989A"><b>img-tps-free-tppg2.testdata.json</b></font> -&gt; img-tps-free-tppg2-20201101230101.testdata.json
lrwxrwxrwx 2 erimsa erimsa        44 Kas  2 02:52 <font color="#06989A"><b>img-tps-free-tppg2.ubi</b></font> -&gt; img-tps-free-tppg2-20201101230101.rootfs.ubi
lrwxrwxrwx 2 erimsa erimsa        46 Kas  2 02:52 <font color="#06989A"><b>img-tps-free-tppg2.ubifs</b></font> -&gt; img-tps-free-tppg2-20201101230101.rootfs.ubifs
-rw-r--r-- 2 erimsa erimsa   4026099 Kas  2 01:17 <font color="#CC0000"><b>img-tps-rmfs-tppg2-20201101221538.rootfs.cpio.gz</b></font>
-rw-r--r-- 2 erimsa erimsa       902 Kas  2 01:16 img-tps-rmfs-tppg2-20201101221538.rootfs.manifest
-rw-r--r-- 2 erimsa erimsa    273762 Kas  2 01:16 img-tps-rmfs-tppg2-20201101221538.testdata.json
lrwxrwxrwx 2 erimsa erimsa        48 Kas  2 01:17 <font color="#06989A"><b>img-tps-rmfs-tppg2.cpio.gz</b></font> -&gt; <font color="#CC0000"><b>img-tps-rmfs-tppg2-20201101221538.rootfs.cpio.gz</b></font>
lrwxrwxrwx 2 erimsa erimsa        49 Kas  2 01:16 <font color="#06989A"><b>img-tps-rmfs-tppg2.manifest</b></font> -&gt; img-tps-rmfs-tppg2-20201101221538.rootfs.manifest
lrwxrwxrwx 2 erimsa erimsa        47 Kas  2 01:16 <font color="#06989A"><b>img-tps-rmfs-tppg2.testdata.json</b></font> -&gt; img-tps-rmfs-tppg2-20201101221538.testdata.json
-rw-rw-r-- 2 erimsa erimsa   2154375 Kas  2 01:19 <font color="#CC0000"><b>modules--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.tgz</b></font>
lrwxrwxrwx 2 erimsa erimsa        59 Kas  2 01:19 <font color="#06989A"><b>modules-tppg2.tgz</b></font> -&gt; <font color="#CC0000"><b>modules--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.tgz</b></font>
-rw-r--r-- 2 erimsa erimsa     26969 Kas  2 01:19 sp7021-bpi-f2p--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
lrwxrwxrwx 2 erimsa erimsa        66 Kas  2 01:19 <font color="#06989A"><b>sp7021-bpi-f2p.dtb</b></font> -&gt; sp7021-bpi-f2p--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
lrwxrwxrwx 2 erimsa erimsa        66 Kas  2 01:19 <font color="#06989A"><b>sp7021-bpi-f2p-tppg2.dtb</b></font> -&gt; sp7021-bpi-f2p--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
-rw-r--r-- 2 erimsa erimsa     26370 Kas  2 01:19 sp7021-bpi-f2s--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
lrwxrwxrwx 2 erimsa erimsa        66 Kas  2 01:19 <font color="#06989A"><b>sp7021-bpi-f2s.dtb</b></font> -&gt; sp7021-bpi-f2s--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
lrwxrwxrwx 2 erimsa erimsa        66 Kas  2 01:19 <font color="#06989A"><b>sp7021-bpi-f2s-tppg2.dtb</b></font> -&gt; sp7021-bpi-f2s--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
-rw-r--r-- 2 erimsa erimsa     24493 Kas  2 01:19 sp7021-demov2--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
lrwxrwxrwx 2 erimsa erimsa        65 Kas  2 01:19 <font color="#06989A"><b>sp7021-demov2.dtb</b></font> -&gt; sp7021-demov2--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
lrwxrwxrwx 2 erimsa erimsa        65 Kas  2 01:19 <font color="#06989A"><b>sp7021-demov2-tppg2.dtb</b></font> -&gt; sp7021-demov2--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
-rw-r--r-- 2 erimsa erimsa     26370 Kas  2 01:19 sp7021-demov3--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
lrwxrwxrwx 2 erimsa erimsa        65 Kas  2 01:19 <font color="#06989A"><b>sp7021-demov3.dtb</b></font> -&gt; sp7021-demov3--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
lrwxrwxrwx 2 erimsa erimsa        65 Kas  2 01:19 <font color="#06989A"><b>sp7021-demov3-tppg2.dtb</b></font> -&gt; sp7021-demov3--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
-rw-r--r-- 2 erimsa erimsa     25944 Kas  2 01:19 sp7021-ev--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
lrwxrwxrwx 2 erimsa erimsa        61 Kas  2 01:19 <font color="#06989A"><b>sp7021-ev.dtb</b></font> -&gt; sp7021-ev--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
lrwxrwxrwx 2 erimsa erimsa        61 Kas  2 01:19 <font color="#06989A"><b>sp7021-ev-tppg2.dtb</b></font> -&gt; sp7021-ev--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
-rw-r--r-- 2 erimsa erimsa     28672 Kas  2 10:24 sp7021-ltpp3g2revD--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
lrwxrwxrwx 2 erimsa erimsa        70 Kas  2 01:19 <font color="#06989A"><b>sp7021-ltpp3g2revD.dtb</b></font> -&gt; sp7021-ltpp3g2revD--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
lrwxrwxrwx 2 erimsa erimsa        70 Kas  2 01:19 <font color="#06989A"><b>sp7021-ltpp3g2revD-tppg2.dtb</b></font> -&gt; sp7021-ltpp3g2revD--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
-rw-r--r-- 2 erimsa erimsa     27928 Kas  2 01:19 sp7021-ublox--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
lrwxrwxrwx 2 erimsa erimsa        64 Kas  2 01:19 <font color="#06989A"><b>sp7021-ublox.dtb</b></font> -&gt; sp7021-ublox--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
lrwxrwxrwx 2 erimsa erimsa        64 Kas  2 01:19 <font color="#06989A"><b>sp7021-ublox-tppg2.dtb</b></font> -&gt; sp7021-ublox--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.dtb
-rwxr-xr-x 1 erimsa erimsa      3862 Kas  2 03:02 <font color="#4E9A06"><b>sp_make.mk</b></font>
drwxr-xr-x 2 erimsa erimsa      4096 Kas  2 10:24 <font color="#3465A4"><b>sp_out</b></font>
drwxr-xr-x 3 erimsa erimsa      4096 Kas  2 01:16 <font color="#3465A4"><b>sp_tools</b></font>
-rwxr-xr-x 2 erimsa erimsa       304 Kas  2 01:16 <font color="#4E9A06"><b>sync.sh</b></font>
-rw-r--r-- 2 erimsa erimsa       234 Kas  2 02:52 ubinize-img-sp-tiny-tppg2-20201101230101.cfg
-rw-r--r-- 2 erimsa erimsa       237 Kas  2 02:52 ubinize-img-tps-free-tppg2-20201101230101.cfg
-rw-r--r-- 2 erimsa erimsa    429146 Kas  2 01:18 u-boot-a7021_emmc-gh-r0.bin
-rw-r--r-- 2 erimsa erimsa    622606 Kas  2 01:18 u-boot-a7021_nand-gh-r0.bin
-rw-r--r-- 2 erimsa erimsa    416692 Kas  2 01:18 u-boot-a7021_ppg2-gh-r0.bin
-rw-r--r-- 2 erimsa erimsa    389882 Kas  2 01:18 u-boot-a7021_romt-gh-r0.bin
lrwxrwxrwx 2 erimsa erimsa        27 Kas  2 01:18 <font color="#06989A"><b>u-boot.bin</b></font> -&gt; u-boot-a7021_ppg2-gh-r0.bin
lrwxrwxrwx 2 erimsa erimsa        27 Kas  2 01:18 <font color="#06989A"><b>u-boot.bin-a7021_emmc</b></font> -&gt; u-boot-a7021_emmc-gh-r0.bin
lrwxrwxrwx 2 erimsa erimsa        27 Kas  2 01:18 <font color="#06989A"><b>u-boot.bin-a7021_nand</b></font> -&gt; u-boot-a7021_nand-gh-r0.bin
lrwxrwxrwx 2 erimsa erimsa        27 Kas  2 01:18 <font color="#06989A"><b>u-boot.bin-a7021_ppg2</b></font> -&gt; u-boot-a7021_ppg2-gh-r0.bin
lrwxrwxrwx 2 erimsa erimsa        27 Kas  2 01:18 <font color="#06989A"><b>u-boot.bin-a7021_romt</b></font> -&gt; u-boot-a7021_romt-gh-r0.bin
lrwxrwxrwx 2 erimsa erimsa        27 Kas  2 01:18 <font color="#06989A"><b>u-boot-tppg2.bin</b></font> -&gt; u-boot-a7021_ppg2-gh-r0.bin
lrwxrwxrwx 2 erimsa erimsa        27 Kas  2 01:18 <font color="#06989A"><b>u-boot-tppg2.bin-a7021_emmc</b></font> -&gt; u-boot-a7021_emmc-gh-r0.bin
lrwxrwxrwx 2 erimsa erimsa        27 Kas  2 01:18 <font color="#06989A"><b>u-boot-tppg2.bin-a7021_nand</b></font> -&gt; u-boot-a7021_nand-gh-r0.bin
lrwxrwxrwx 2 erimsa erimsa        27 Kas  2 01:18 <font color="#06989A"><b>u-boot-tppg2.bin-a7021_ppg2</b></font> -&gt; u-boot-a7021_ppg2-gh-r0.bin
lrwxrwxrwx 2 erimsa erimsa        27 Kas  2 01:18 <font color="#06989A"><b>u-boot-tppg2.bin-a7021_romt</b></font> -&gt; u-boot-a7021_romt-gh-r0.bin
lrwxrwxrwx 2 erimsa erimsa        58 Kas  2 01:19 <font color="#06989A"><b>uImage</b></font> -&gt; uImage--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.bin
-rw-r--r-- 2 erimsa erimsa   4329680 Kas  2 01:19 uImage--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.bin
-rw-r--r-- 2 erimsa erimsa   8338128 Kas  2 01:19 uImage-initramfs--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.bin
lrwxrwxrwx 2 erimsa erimsa        68 Kas  2 01:19 <font color="#06989A"><b>uImage-initramfs-tppg2.bin</b></font> -&gt; uImage-initramfs--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.bin
lrwxrwxrwx 2 erimsa erimsa        58 Kas  2 01:19 <font color="#06989A"><b>uImage-tppg2.bin</b></font> -&gt; uImage--5.4.35+git0+5cd489883f-r0-tppg2-20201101221538.bin
-rw-r--r-- 2 erimsa erimsa      1984 Kas  2 01:16 upd_bad.its
-rw-r--r-- 2 erimsa erimsa       670 Kas  2 01:16 upd_b_KLM601.its
-rw-r--r-- 2 erimsa erimsa       664 Kas  2 01:16 upd_b_tpp.its
-rw-r--r-- 2 erimsa erimsa      2250 Kas  2 01:16 upd_fwuploader.its
-rw-r--r-- 2 erimsa erimsa       721 Kas  2 01:16 upd_KLM601-revB-b.its
-rw-r--r-- 2 erimsa erimsa      2272 Kas  2 01:16 upd_KLM601-revB.its
-rw-r--r-- 2 erimsa erimsa      2272 Kas  2 01:16 upd_KLM601-revC.its
-rw-r--r-- 2 erimsa erimsa      2257 Kas  2 01:16 upd_KLM601-revT.its
-rwxr-xr-x 2 erimsa erimsa        84 Kas  2 01:16 <font color="#4E9A06"><b>upd.mk</b></font>
-rw-r--r-- 2 erimsa erimsa      2256 Kas  2 01:16 upd_TPS3-agent.its
-rw-r--r-- 2 erimsa erimsa      2214 Kas  2 01:16 upd_TPS3-db.its
-rw-r--r-- 2 erimsa erimsa      2252 Kas  2 01:16 upd_TPS3-node.its
-rw-r--r-- 2 erimsa erimsa      2255 Kas  2 01:16 upd_TPS3-rlp.its</pre>

<pre><font color="#4E9A06"><b>erimsa@probook</b></font>:<font color="#3465A4"><b>~</b></font>$ ls -l /disk2/build.26/tmp/deploy/images/tppg2-arm5
total 2192
-rw-r--r-- 1 erimsa erimsa   49088 Kas  2 02:19 a926.bin
-rw-rw-r-- 1 erimsa erimsa       0 Kas  2 02:52 a926-empty.bin
-rw-r--r-- 2 erimsa erimsa 1886411 Kas  2 03:02 <font color="#CC0000"><b>img-xboot-tppg2-arm5-20201101230101.rootfs.cpio.gz</b></font>
-rw-r--r-- 2 erimsa erimsa     180 Kas  2 03:02 img-xboot-tppg2-arm5-20201101230101.rootfs.manifest
-rw-r--r-- 2 erimsa erimsa  243707 Kas  2 03:02 img-xboot-tppg2-arm5-20201101230101.testdata.json
lrwxrwxrwx 2 erimsa erimsa      50 Kas  2 03:02 <font color="#06989A"><b>img-xboot-tppg2-arm5.cpio.gz</b></font> -&gt; <font color="#CC0000"><b>img-xboot-tppg2-arm5-20201101230101.rootfs.cpio.gz</b></font>
lrwxrwxrwx 2 erimsa erimsa      51 Kas  2 03:02 <font color="#06989A"><b>img-xboot-tppg2-arm5.manifest</b></font> -&gt; img-xboot-tppg2-arm5-20201101230101.rootfs.manifest
lrwxrwxrwx 2 erimsa erimsa      49 Kas  2 03:02 <font color="#06989A"><b>img-xboot-tppg2-arm5.testdata.json</b></font> -&gt; img-xboot-tppg2-arm5-20201101230101.testdata.json
drwxr-xr-x 4 erimsa erimsa    4096 Kas  2 10:24 <font color="#3465A4"><b>sp_tools</b></font>
-rw-r--r-- 1 erimsa erimsa   22520 Kas  2 02:52 xboot-emmc.bin
-rw-r--r-- 1 erimsa erimsa   26192 Kas  2 02:52 xboot-nand.bin
</pre>

**Comment by dmitrydvorkin** [comment]
interesting! Do you have space on your /disk2/ fs? What is the FS type?
Looks like file creation error or kind of async FS behaviour

**Comment by erimsa** [comment]
Fstype of Host is ext4  and there are space 

<pre><b>Device</b>         <b>  Start</b> <b>       End</b> <b>  Sectors</b> <b>  Size</b> <b>Type</b>
/dev/nvme0n1p1    2048    1050623   1048576   512M EFI System
/dev/nvme0n1p2 1050624 1000214527 999163904 476,4G Linux filesystem
</pre>

**Comment by erimsa** [comment]
I didnt create a full partion for disk2 folder. I simple mkdir to root using :  "mkdir -p /disk2 && chmod 777 /disk2"
But my system runs on a NVMe disk.

**Comment by dmitrydvorkin** [comment]
I have both types: separate hdd for /disk2 and just the folder on another PC.
Linux Filesystem - is it ext4 with default "noatime" only option?
Hmm.. Did you run sp_make.mk before on this disk successfully?

**Comment by erimsa** [comment]
Sorry I didn't mention. I change the PC.  Old one was has HDD with ext4 (ubuntu 18.04 OS). 
I will check the mount option of the new system.

**Comment by erimsa** [comment]
I changed build to another disk but it didn't make any difference, same error output .
The whole output of "make -f ./sp_make" 

<pre>install -d ./sp_out/
install ../tppg2-arm5/xboot-emmc.bin ./sp_out/xboot.bin
./sp_tools/secure_sign/gen_signature.sh ./sp_out xboot.bin 0
**************************************
*** Warning: Sign with TEST key !! ***
*** Please put real keys in keys/. ***
**************************************
Private key: ./sp_tools/secure_sign/sign_keys/test-keys/key_priv_0.hex
Public key : ./sp_tools/secure_sign/sign_keys/test-keys/key_pub_0.hex
Sign and verify signature OK.
key_pub    : 0xAC, 0xE4, 0x68, 0x98, 0x89, 0x68, 0x75, 0x2B, 0x91, 0x61, 0xF7, 0x3F, 0x9B, 0x72, 0x98, 0x34, 0xA8, 0xF5, 0x68, 0xE1, 0xA2, 0x05, 0x60, 0x0F, 0x7D, 0xDE, 0xBC, 0xCE, 0xDE, 0x87, 0x40, 0x5C
Signature  : 0x8E, 0x70, 0x7B, 0x2E, 0x83, 0x32, 0x9A, 0xE0, 0xBB, 0x58, 0xE1, 0xA7, 0x84, 0x1B, 0xAF, 0xAF, 0x71, 0xD3, 0xCF, 0x7C, 0x34, 0xB5, 0xDD, 0x3B, 0xAD, 0x98, 0xC7, 0x27, 0xB3, 0xA2, 0xD8, 0x36, 0x01, 0x99, 0x20, 0x0B, 0xC3, 0xC0, 0x41, 0xCC, 0x11, 0x07, 0xD4, 0xBF, 0xA4, 0xEB, 0xBA, 0x82, 0xDD, 0x57, 0x84, 0xF4, 0x84, 0xB1, 0x30, 0x05, 0x32, 0xDC, 0x06, 0x0F, 0xF1, 0x7C, 0x3E, 0x06

Save signature to file: ./sp_out/sign.sig
no need to add sign flag (xboot)
OUT_SIG: ./sp_out/sign.sig
IN_IMG: ./sp_out/xboot.bin
cd ../tppg2-arm5/sp_tools/; ./add_xhdr.sh ../../tppg2/sp_out/xboot.bin ../../tppg2/sp_out/xboot.img 1
chksum=0000c9fc
install ./sp_out/xboot.img ./sp_out/xboot0
install ./sp_out/xboot.img ./sp_out/xboot1
install -d ./sp_out/
export MKIMAGE=./sp_tools/mkimage;  ./sp_tools/add_uhdr.sh nonos_B ../tppg2-arm5/a926-empty.bin sp_out/nonos arm 0x10040 0x10040
./sp_tools/mkimage: Can&apos;t read ../tppg2-arm5/a926-empty.bin: Invalid argument
-rw-rw-r-- 1 erimsa erimsa 64 Kas  5 15:43 sp_out/nonos
size: 64 (hex 40)
install -d ./sp_out/
export MKIMAGE=./sp_tools/mkimage; ./sp_tools/add_uhdr.sh &quot;uboot_pentagram_board&quot; u-boot.bin-a7021_ppg2 sp_out/u-boot.bin-a7021_ppg2 arm 0x200040 0x200040
Image Name:   uboot_pentagram_board
Created:      Thu Nov  5 12:43:38 2020
Image Type:   ARM Linux Sunplus Quick Boot Image (uncompressed)
Data Size:    416692 Bytes = 406.93 KiB = 0.40 MiB
Load Address: 00200040
Entry Point:  00200040
-rw-rw-r-- 1 erimsa erimsa 416756 Kas  5 15:43 sp_out/u-boot.bin-a7021_ppg2
size: 416756 (hex 65bf4)
./sp_tools/secure_sign/gen_signature.sh ./sp_out/ u-boot.bin-a7021_ppg2 1
**************************************
*** Warning: Sign with TEST key !! ***
*** Please put real keys in keys/. ***
**************************************
Private key: ./sp_tools/secure_sign/sign_keys/test-keys/key_priv_0.hex
Public key : ./sp_tools/secure_sign/sign_keys/test-keys/key_pub_0.hex
Sign and verify signature OK.
key_pub    : 0xAC, 0xE4, 0x68, 0x98, 0x89, 0x68, 0x75, 0x2B, 0x91, 0x61, 0xF7, 0x3F, 0x9B, 0x72, 0x98, 0x34, 0xA8, 0xF5, 0x68, 0xE1, 0xA2, 0x05, 0x60, 0x0F, 0x7D, 0xDE, 0xBC, 0xCE, 0xDE, 0x87, 0x40, 0x5C
Signature  : 0x52, 0x01, 0xFE, 0x4A, 0x9D, 0x0D, 0x32, 0x7A, 0x2B, 0x01, 0x76, 0xB1, 0x89, 0x6E, 0x11, 0xD8, 0x32, 0x37, 0xEF, 0x60, 0x53, 0x48, 0x75, 0xC4, 0x76, 0xBC, 0x37, 0x61, 0xFA, 0x4F, 0x45, 0xC4, 0xA7, 0xCA, 0x8F, 0x7B, 0x4E, 0x51, 0x3B, 0x6F, 0xCB, 0x28, 0xE1, 0xC4, 0xAC, 0x86, 0x03, 0xB5, 0x30, 0x7B, 0x29, 0xF0, 0x21, 0xB8, 0x4E, 0x8E, 0x6F, 0x62, 0x84, 0x3F, 0xAC, 0x84, 0xB3, 0x07

Save signature to file: ./sp_out//sign.sig
add sign flag for (uboot/kernel)
install ./sp_out/u-boot.bin-a7021_ppg2 ./sp_out/uboot0
install ./sp_out/u-boot.bin-a7021_ppg2 ./sp_out/uboot1
install ./sp_out/u-boot.bin-a7021_ppg2 ./sp_out/uboot2
install -d ./sp_out/
install uImage-initramfs-tppg2.bin sp_out/uImage-initramfs-tppg2.bin
./sp_tools/secure_sign/gen_signature.sh ./sp_out/ uImage-initramfs-tppg2.bin 1
**************************************
*** Warning: Sign with TEST key !! ***
*** Please put real keys in keys/. ***
**************************************
Private key: ./sp_tools/secure_sign/sign_keys/test-keys/key_priv_0.hex
Public key : ./sp_tools/secure_sign/sign_keys/test-keys/key_pub_0.hex
Sign and verify signature OK.
key_pub    : 0xAC, 0xE4, 0x68, 0x98, 0x89, 0x68, 0x75, 0x2B, 0x91, 0x61, 0xF7, 0x3F, 0x9B, 0x72, 0x98, 0x34, 0xA8, 0xF5, 0x68, 0xE1, 0xA2, 0x05, 0x60, 0x0F, 0x7D, 0xDE, 0xBC, 0xCE, 0xDE, 0x87, 0x40, 0x5C
Signature  : 0xFB, 0x51, 0xF0, 0x79, 0xF3, 0x10, 0x39, 0xE5, 0xCA, 0x91, 0xDF, 0x82, 0x93, 0x07, 0x35, 0x1F, 0xCB, 0x8D, 0xAB, 0x48, 0xA3, 0x95, 0x16, 0xDF, 0x62, 0xAE, 0x5E, 0xC1, 0x4A, 0x62, 0xE6, 0x96, 0x8C, 0xBC, 0xF7, 0x7E, 0xE8, 0x24, 0x51, 0x4C, 0xDA, 0x0A, 0x21, 0x34, 0x31, 0x81, 0xEB, 0x2C, 0x5E, 0xD8, 0x28, 0x1C, 0xCC, 0x5D, 0x7C, 0x64, 0xDA, 0xA8, 0x14, 0x8D, 0xB2, 0xE5, 0x1B, 0x03

Save signature to file: ./sp_out//sign.sig
add sign flag for (uboot/kernel)
install ./sp_out/uImage-initramfs-tppg2.bin ./sp_out/kernel
install -d ./sp_out/
ln -f -s `pwd`/sp7021-ltpp3g2revD.dtb `pwd`/sp_out/dtb
install -d ./sp_out/
ln -f -s `pwd`/img-tps-free-tppg2.ext4 `pwd`/sp_out/rootfs
./sp_tools/isp pack_image ./sp_out/ISPBOOOT.BIN \
./sp_out/xboot0 \
./sp_out/uboot0 \
./sp_out/xboot1 0x100000 \
./sp_out/uboot1 0x100000 \
./sp_out/uboot2 0x100000 \
./sp_out/env 0x80000 \
./sp_out/env_redund 0x80000 \
./sp_out/nonos 0x100000 \
./sp_out/dtb 0x40000 \
./sp_out/kernel 0x2000000 \
./sp_out/rootfs 0x1E000000
Error for &apos;isp_script_nand_003f4093&apos;: isp.c: 1131
make: *** [sp_make.mk:86: sp_out/ISPBOOOT.BIN] Error 255
</pre>

**Comment by erimsa** [comment]
I suspect about that line of output ; 
"./sp_tools/mkimage: Can't read ../tppg2-arm5/a926-empty.bin: Invalid argument"

Which the a926-empty.bin file exist in  tppg2-arm5 folder the size is 0.

**Comment by dmitrydvorkin** [comment]
Good catch!
you can create zero-size file ../tppg2-arm5/a926-empty.bin:
$ touch ../tppg2-arm5/a926-empty.bin

or you can set F_NON=a926.bin
at lines 20-22 in sp_make.mk

This file is meanless for you: it contains B-Chip code, that is made just or demo.

P.S.Hmm... strange. I have this file creation at
https://github.com/tibbotech/yocto_layers/blob/d206745be793fa20c0ea355ab7c3f71a8cea40cd/meta-sunplus/recipes-bsp/b-chip/bnoos.inc#L21
Why it is not working for you, but works for me?

P.P.S. Did you run the script successfully?

**Comment by erimsa** [comment]
No, it didn't help either. The file (a926-empty.bin) was in the place ../tppg2-arm5
I tried, 
 1. create a new arm926-empty.bin with "touch ../tppg2-arm5/arm926-empty.bin" then run make -f ./sp_make.mk
 2. Changed F_NON=a926.bin and then run make -f ./sp_make.mk

At the end of make output is the same ;
<pre>Error for &apos;isp_script_nand_000017ca&apos;: isp.c: 1131
make: *** [sp_make.mk:86: sp_out/ISPBOOOT.BIN] Error 255
</pre>

**Comment by erimsa** [comment]
I tried almost everything and results are the same. I started from the beginning with removing all resources. 
Only difference that I suspect the Host System (Ubuntu 18.04) running on a NVMe disk. 
I will try to build on a HDD disk I hope does'nt end with the same result.

**Comment by dmitrydvorkin** [comment]
I think the problem is in unlink() logic inside isp.c.
Lets test tomorrow. I'll push the new sources in the evening

**Comment by dmitrydvorkin** [comment]
Please, check the [last update](https://github.com/tibbotech/yocto_layers/commit/01dad0084dd5797a615c812e3f8d2972ab8a9648). Found the PATH problem on some host systems and fixed it.

**Comment by erimsa** [comment]
It worked, thanks.
