### ISSUE TITLE
Cloning layers procedure not up to date anymore

### ISSUE THREAD

**Issue by btrhad** [tibbotech/yocto_layers#15]
Last Thursday (may 19th) the openamp repo was updated to support more recent yocto releases.
gatesgarth was removed and replaced with honister and kirkstone.

so the patch line in the readme (step 1.1 Cloning layers) should be upgraded to:

`sed -i 's/"honister"/"rocko sumo thud zeus dunfell gatesgarth honister kirkstone"/g' ./poky/meta-openamp/conf/layer.conf`

Henk

**Comment by dmitrydvorkin** [comment]
fixed, thanks!
