### ISSUE TITLE
linux-sprel recipe do_patch fails

### ISSUE THREAD

**Issue by erimsa** [tibbotech/yocto_layers#3]
It seems it tries to patch multiple times. Especially 
rpi-ovls patches. 

I tried to solve but no success yet.

**Comment by dmitrydvorkin** [comment]
Did you try to cleanup the kernel source and rebuild?
$ bitbake -c cleanall virtual/kernel && bitbake img-spmn

May i see the error log if problem will not be resolved with cleanup?

**Comment by erimsa** [comment]
After clean and bitbake img-spmn problem is solved. Closing the issue.
