### ISSUE TITLE
typo here

### ISSUE THREAD

**Issue by ghost** [tibbotech/yocto_layers#5]
Hi
In the build section
. oe-init-build-env c.tppg2 should be
source oe-init-build-env c.tppg2

Is that right?

Alex

**Comment by dmitrydvorkin** [comment]
"." and "source" means the same in almost all traditional shells:
https://ss64.com/bash/source.html

"source is a synonym for dot/period '.' in bash, but not in POSIX sh, so for maximum compatibility use the period."

**Comment by ghost** [comment]
You are missing the slash

**Comment by dmitrydvorkin** [comment]
really? where?

**Comment by dmitrydvorkin** [comment]
> You are missing the slash
Really? Where?

**Comment by dmitrydvorkin** [comment]
Really? Where?

**Comment by ghost** [comment]
in the README.md, under build, it says ". oe-init-build-env c.tppg2" instead of "./oe-init-build-env c.tppg2"

**Comment by dmitrydvorkin** [comment]
ah, "./" is not required:

[dv@localhost poky (zeus)]$ . oe-init-build-env c.tppg2 

### Shell environment set up for builds. ###

You can now run 'bitbake <target>'
....
