### ISSUE TITLE
mode-sqlite3 bash

### ISSUE THREAD

**Issue by maku0** [tibbotech/yocto_layers#6]
I'm building image for LTPP3 for the first time and I have these error:

ERROR: node-sqlite3-4.1.1-r0 do_package_qa: QA Issue: /usr/lib/node_modules/sqlite3/node_modules/node-gyp/test/docker.sh contained in package node-sqlite3-node-gyp requires /bin/bash, but no providers found in RDEPENDS_node-sqlite3-node-gyp? [file-rdeps]
ERROR: node-sqlite3-4.1.1-r0 do_package_qa: QA Issue: /usr/lib/node_modules/sqlite3/node_modules/node-gyp/gyp/samples/samples contained in package node-sqlite3-node-gyp requires /usr/bin/python, but no providers found in RDEPENDS_node-sqlite3-node-gyp? [file-rdeps]
ERROR: node-sqlite3-4.1.1-r0 do_package_qa: QA Issue: /usr/lib/node_modules/sqlite3/tools/docker/architecture/linux-arm64/Dockerfile contained in package node-sqlite3 requires /bin/echo, but no providers found in RDEPENDS_node-sqlite3? [file-rdeps]
ERROR: node-sqlite3-4.1.1-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: Logfile of failure stored in: /disk2/build.24/tmp/work/cortexa9hf-neon-tps-linux-gnueabi/node-sqlite3/4.1.1-r0/temp/log.do_package_qa.58248
ERROR: Task (/usr/yoctoPlus2/poky/c.tppg2/../meta-tibbo/recipes-core/node-modules/node-sqlite3_4.1.1.bb:do_package_qa) failed with exit code '1'

**Comment by dmitrydvorkin** [comment]
please, see my last yocto_layers update. this problem is resolved
