### ISSUE TITLE
d96f8577c is not a valid commit ID

### ISSUE THREAD

**Issue by maku0** [tibbotech/yocto_layers#7]
I have error, situation is weird becouse that commit ID really exist in yocto_layers.

ERROR: mc:tpp-tppg2:linux-sprel-4.19.37+gitAUTOINC+ac3527cae6-r0 do_validate_branches: 7bf03ca60187927d02779c9857b14b3d96f8577c is not a valid commit ID.
ERROR: mc:tpp-tppg2:linux-sprel-4.19.37+gitAUTOINC+ac3527cae6-r0 do_validate_branches: The kernel source tree may be out of sync
ERROR: mc:tpp-tppg2:linux-sprel-4.19.37+gitAUTOINC+ac3527cae6-r0 do_validate_branches: Execution of '/disk2/build.24/tmp/work/tppg2-tps-linux-gnueabi/linux-sprel/4.19.37+gitAUTOINC+ac3527cae6-r0/temp/run.do_validate_branches.4452' failed with exit code 1:
fatal: git cat-file: could not get object info
WARNING: exit code 1 from a shell command.

**Comment by dmitrydvorkin** [comment]
look at your poky/meta-tibbo/conf/machine/include/tppg2-all-prefs.inc, line #30
do you have
linux_v = "sprel"
there?

maybe you should clean the kernel recipe and try again:
$ bitbake -c cleanall virtual/kernel && bitbake img-spmn

**Comment by maku0** [comment]
I have linux_v = "sprel", cleanll helped, thanks.
Now I have another error:

ERROR: mc:tpp-tppg2:img-sp-tiny-1.0-r1 do_prepare_recipe_sysroot: The file /usr/lib/node is installed by both node-red-contrib-modbus and node-nvd3, aborting
ERROR: mc:tpp-tppg2:img-tps-free-1.0-r1 do_prepare_recipe_sysroot: The file /usr/lib/node is installed by both node-red-contrib-modbus and node-nvd3, aborting

**Comment by dmitrydvorkin** [comment]
the instructions in "Clonning layers" of this release was updated in the README, please, take a look at the yocto_layers github page.
patch -p0 < ./npm.patch
is mentioned at the end of the instructions.
If you pull the new tibbo_layers, please, patch your meta/.../npm.bbclass
This problem cased by changes between NPM default modules location in different Node releases.

Don't forget to cleanall the failed recipes after that:
$ bitbake -c cleanall mc:tpp-tppg2:node-red-contrib-modbus && bitbake -c cleanall mc:tpp-tppg2:node-nvd3 && bitbake img-spmn

**Comment by maku0** [comment]
After patch it works. Thans, but I had to edit npm.bbclass manualy. Patch returns error:

km@ubuntu:/usr/yoctoPlus2/poky$ patch -p0 < ./npm.patch
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- poky/meta/classes/npm.bbclass	2020-05-14 11:10:50.920541874 +0300
|+++ poky/meta/classes/npm.bbclass	2020-05-14 11:10:54.592541839 +0300
--------------------------
File to patch: ^C

**Comment by dmitrydvorkin** [comment]
you're inside ./poky/ so you may use -p1 option:
patch -p1 < ./npm.patch
