### ISSUE TITLE
SD card image.

### ISSUE THREAD

**Issue by maku0** [tibbotech/yocto_layers#9]
Does your Yocto provide image of the SD card? I have tried file ISPBOOOT.BIN from boot2linux_SDcard directory but it doesnt have valid partitions. Also other BIN files from sp_out.

**Comment by dmitrydvorkin** [comment]
_SDcard is for SD.
That's strange case we use the same codebase. Can you show me your firmware upload log?

Yes, we publish ISPBOOOT.BIN there:
https://tibbo.com/downloads/LTPS/FW/LTPPg2/

you may try ISPBOOOT.BIN-v15. It includes Tibbo WebInterface.
BTW, the Yocto Layers update is coming today an tomorrow!

**Comment by dmitrydvorkin** [comment]
you may try ISPBOOOT.BIN-v15. It includes Tibbo WebInterface.
BTW, the Yocto Layers update is coming today an tomorrow!

**Comment by maku0** [comment]
My goal is to get bootable SD card. I would like to run Linux from SD card until I finish development process. When I finish it I would like to run Linux from internal EMMC memory.
In Howto doc you wrote:

> After build /disk2/build.24/tmp/deploy/images/tppg2/ contains all required image components: bootloaders, kernel, rootfs images. Pack the final image:
> 
> $ cd /disk2/build.24/tmp/deploy/images/tppg2/
> $ make -f ./sp_make.mk
> 
> ISPBOOOT.BIN is in the ./sp_out/

After Yocto compilation and I have files:
km@ubuntu:/disk2/build.24/tmp/deploy/images/tppg2/sp_out$ tree
.
├── boot2linux
│   └── ISPBOOOT.BIN
├── boot2linux_SDcard
│   └── ISPBOOOT.BIN
├── dtb -> /disk2/build.24/tmp/deploy/images/tppg2/sp7021-ltpp3g2revD.dtb
├── env
├── env_redund
├── ISPBOOOT.BIN
├── kernel
├── nonos
├── rootfs -> /disk2/build.24/tmp/deploy/images/tppg2/img-sp-tiny-tppg2.ext4
├── uboot0
├── uboot1
├── uboot2
├── u-boot.bin-a7021_ppg2
├── uImage
├── xboot0
├── xboot1
├── xboot.bin
└── xboot.img

2 directories, 18 files

I expect that in boot2linux_SDcard I will get SD card image with whole Linux rootfs, uboot, uImage etc.  ISPBOOOT.BIN doesnt work after dd it to SD card.

**Comment by dmitrydvorkin** [comment]
bootloader requires FAT32 with block size 2048 on SD card

https://superuser.com/questions/1286135/what-allocation-unit-size-to-use-when-formatting-a-usb-flash-drive-in-fat32

dd? you need to just copy the file into SD card's FAT.
to be able to boot from SD you need to wire both jumpers: CN10 and CN11.

So to boot from USB (and flash) you need to wire CN10 jumper only,
to boot from SD - both: CN10,CN11.

I'll discover the possible image issue today and give you the report

**Comment by maku0** [comment]
Hi, I have succesfully compiled newest yocto, but still I dont know what I should do to create SD card with linux.
In other distributions like Beaglebone you get image of SD card and you have to just copy it using eg. dd. This is best option for me, I dont have to fight with these all files in /disk2/build.24/tmp/deploy/images/tppg2
Another way is to update your README.md and write how to create SD card, or write some script.

**Comment by maku0** [comment]
I've used script sdcard_boot.sh from SunpPlus and I got SD card image. Command: make -f sp_make.mk ISP_SDCARD
But during boot I have error:

> {{sdcard_isp}}
finding file
[d] fat/fat_boot.c :181
[d] fat/fat_boot.c :195
[d] sdmmc/drv_sd_mmc.c :21
InitChipCtrl
busclk=200000 div=1012
[d] sdmmc/drv_sd_mmc.c :23
IdentifyStorage
[d] sdmmc/hal_sd_mmc.c :1505
0x000000AA
0x00000001
High Cap
[d] sdmmc/hal_sd_mmc.c :467
[d] sdmmc/hal_sd_mmc.c :478
SPEC=0 BUS_WIDTHS=5
4bit mode
busclk=5000000 div=40
[d] sdmmc/hal_sd_mmc.c :1697
[d] sdmmc/drv_sd_mmc.c :33
[d] fat/fat_boot.c :219
[d] fat/fat_boot.c :231
part@0x00000800
[d] fat/fat_boot.c :260
[d] fat/fat_boot.c :296
[d] fat/fat_boot.c :316
[d] fat/fat_boot.c :320
[d] fat/fat_boot.c :323
[d] fat/fat_boot.c :323
[d] fat/fat_boot.c :323
[d] fat/fat_boot.c :323
[d] fat/fat_boot.c :323
[d] fat/fat_boot.c :323
[d] fat/fat_boot.c :323
[d] fat/fat_boot.c :323
[d] fat/fat_boot.c :367
Run draiminit@0x9E805CD5
Done draiminit
dram test 0x00800000 - 0x00800400
sdcard do boot mode !!!!!
fat load uboot
bad mgaic
failed to load uboot
Not support boot mode 0x7 in this build
ROM> d:dump, f:fill, r:read, w:write, l:lreg, W:wreg, m:menu, K:reset, q: quit
ROM>


[sp_make.mk.txt](https://github.com/tibbotech/yocto_layers/files/4911613/sp_make.mk.txt)
[sdcard_boot.sh.txt](https://github.com/tibbotech/yocto_layers/files/4911614/sdcard_boot.sh.txt)

**Comment by dmitrydvorkin** [comment]
thank you! Hope, I'll have a chance to study problem in-depth tomorrow...

**Comment by maku0** [comment]
Hi, Are you going to resolve these isue?

**Comment by dmitrydvorkin** [comment]
already resolved. Please, see last commit in the "dunpfell" branch.
In short: no need special image for SD card to be able to flash from SD.
Insert FAT32-formatted SD card with ISPBOOOT.BIN, short both CN10 and CN11 and reset the board. It will be flashed

**Comment by erimsa** [comment]
It seems SPI-NAND flash can not be used after this commit. (For custom hardware ) Am I right?

**Comment by dmitrydvorkin** [comment]
there are 3 modifications are done:
1) off spi_nor at ltpp3g2 dts in kernel
2) off spi_nor at ltpp3g2 dts in u-boot (just the copy)
3) xboot: spi_nor is off if the bootdev != spi nor

(1),(2) made by me
(3) made by SP. Theoretically, you're right: (3) may cause trouble if you're flashing to NOR from any other storage. need to double-check...

**Comment by erimsa** [comment]
I mean Nand flash not Nor flash but however 83. pin is not releated Spi Nor or Nand according to reference schematics and other boards. I could'nt get exactly.

**Comment by dmitrydvorkin** [comment]
it is related to SPI NOR flash. SPI NOR group of pins is enabled at iBoot (in ROM), but for LTPP3G2 this pin is dedicated to WiFi (SDIO) additional reset function. So I need a way to switch off the SPI NOR muxing in xBoot, u-boot or in kernel for LTPP3G2.
There are several groups of pins are enabled at iBoot to be able to boot from several different media.
Some of them may be used in another configurations.

So if user may experience problems of non-working functionality and will not be able to realize the muxing problem unless he will see the mux list and understand that some pin is taken by another function that he does not need and did not configured in DTS.

To switch it off for your individual configuration you need to modify the xBoot source code or do it strictly in u-boot or in kernel.

I add the functionality to switch off any predefined groups to not to have surprises like I had: SDIO is working, but I can't communicate with the chip, case additional GPIO Reset pin required for the WiFi is taken by preset, activated in iBoot group.

the most flexible way is to setup zero_group in the DTS. That's what I've done. Zero groups are the first that is activated at kernel and u-boot so theere is the guarantee that you'll not have unwanted groups before you'll activated your functionality in the DTS nodes.

SP guys think it should be also done in xBoot. I'll double check they modification. Thanks for your doubts on this issue!

Upd: verifyed. It is OK. May I close this problem?

**Comment by erimsa** [comment]
Thanks, that comment made it clear about pin issue. 
I have'nt tried yet SD card image.

**Comment by dmitrydvorkin** [comment]
did you try?

**Comment by erimsa** [comment]
Not yet, will do it in this weekend.

**Comment by erimsa** [comment]
Tried SD Card flash but no success. SD Card formatted FAT32 and copied ISPBOOOT.BIN to card. 
CN10 and CN11 shorted.
The output is : (repeatedly these lines )

<pre>[sdcard]
card pin=1
[d] bootmain.c :116
dev=3 pin=1
[d] iboot.c :364
find file
[d] fat_boot.c :181
[d] fat_boot.c :195
[d] drv_sd_mmc.c :21
InitChipCtrl
busclk=200000 div=1012
[d] drv_sd_mmc.c :23
IdentifyStorage
[d] hal_sd_mmc.c :1521
0x000000AA
0x00000001
High Cap
[d] hal_sd_mmc.c :483
[d] hal_sd_mmc.c :494
SPEC=2 BUS_WIDTHS=5
busclk=5000000 div=40
[d] hal_sd_mmc.c :1717
[d] drv_sd_mmc.c :33
[d] fat_boot.c :218
[d] fat_boot.c :230
part@0x00000001
[d] fat_boot.c :259
Not fat32
[d] iboot.c :285
SD1 not found
[d] iboot.c :877
hw_cfg=0x00007BFF
bootmode=0x00000007
[d] iboot.c :820

[sdcard]
card pin=1
[d] bootmain.c :116
dev=3 pin=1
[d] iboot.c :364
find file
[d] fat_boot.c :181
[d] fat_boot.c :195
[d] drv_sd_mmc.c :21
InitChipCtrl
busclk=200000 div=1012
[d] drv_sd_mmc.c :23
IdentifyStorage
[d] hal_sd_mmc.c :1521
0x000000AA
0x00000001
High Cap
[d] hal_sd_mmc.c :483
[d] hal_sd_mmc.c :494
SPEC=2 BUS_WIDTHS=5
busclk=5000000 div=40
[d] hal_sd_mmc.c :1717
[d] drv_sd_mmc.c :33
[d] fat_boot.c :218
[d] fat_boot.c :230
part@0x00000001
[d] fat_boot.c :259
Not fat32
[d] iboot.c :285
SD1 not found
[d] iboot.c :877
hw_cfg=0x00007BFF
bootmode=0x00000007
[d] iboot.c :820

[sdcard]
card pin=1
[d] bootmain.c :116
dev=3 pin=1
[d] iboot.c :364
</pre>

**Comment by erimsa** [comment]
And I think what @maku0 ask about is booting from SDCard not flash eMMC trough SDCard. If I understand correctly.

**Comment by maku0** [comment]
Exactly, boot from SD.
Yesterday I've builded your yocto image from https://sunplus-tibbo.atlassian.net/wiki/spaces/doc/pages/506757122/2.+HOW+TO+GET+SOURCE+FILE+AND+PACKAGE
and It doesnt still doesnt boot properly. 

[sdcard]
card pin=1
[d] bootmain.c :116
dev=3 pin=1
[d] iboot.c :364
find file
[d] fat_boot.c :181
[d] fat_boot.c :195
[d] drv_sd_mmc.c :21
InitChipCtrl
busclk=200000 div=1012
[d] drv_sd_mmc.c :23
IdentifyStorage
[d] hal_sd_mmc.c :1521
Rsp timeout (0)
 CMD:8 SD status0=0x00000075 status1=0x00002200
RxRsp end err=0x00000002
cmd:80x00000002
0x0000000F
Rsp timeout (0)
 CMD:55 SD status0=0x00000075 status1=0x00002200
RxRsp end err=0x00000002
cmd:55Rsp timeout (0)
 CMD:41 SD status0=0x00000075 status1=0x00002200
RxRsp end err=0x00000002
cmd:41[d] hal_sd_mmc.c :1722
[d] drv_sd_mmc.c :33
[d] fat_boot.c :213
[d] iboot.c :285
SD1 not found
[d] iboot.c :877
hw_cfg=0x00007FFF
bootmode=0x00000007
[d] iboot.c :820

**Comment by dmitrydvorkin** [comment]
https://github.com/tibbotech/yocto_layers/blob/dunfell/meta-tibbo/docs/booting/boot_sd.md
